[package]
name = "chess"
version = "0.1.0"
authors = ["theor <theo.richart@gmail.com>"]

[dependencies]
lazy_static = "1.3.0"
bitflags = "1.0.4"
galvanic-assert = "0.8.7"
log = "*"
simplelog = "*"
rand = "0.6.5"